server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.xigua.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    dbcp2:
      min-idle: 5
      max-total: 5
      initial-size: 5
eureka:
  client: # 将客户端注册进eureka中，地址就是7001项目里面暴露的地址。
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8001 # 给服务端做别名处理
    prefer-ip-address: true # 地址默认显示ip地址

info:
  app.name: xigua-microservicecloud
  acompany.name: xigua
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
