server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gataway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: root
    dbcp2:
      min-idle: 5
      max-total: 5
      initial-size: 5
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com #host映射文件
    prefer-ip-address: true # 显示ip

# 配置zuul的地址映射
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: microservicecloud-dept
  prefix: xigua


info:
  app.name: xigua
  company.name: xigua
  build.artifactid: ${project.artifactid}
  build.version: ${project.version}